# Generated by Django 5.1.1 on 2024-10-29 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='blog',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.blog'),
        ),
    ]
